# Generated by Django 5.2.1 on 2025-06-18 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_categoryclothing_productclothing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryclothing',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='categoryclothing',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='productclothing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.categoryclothing', verbose_name='Категория'),
        ),
    ]
