# Generated by Django 5.2.1 on 2025-06-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_categoryclothing_options_categoryclothing_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclothing',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
