# Generated by Django 5.2.1 on 2025-06-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_productclothing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryclothing',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productclothing',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
