# Generated by Django 5.2.1 on 2025-06-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_categoryclothing_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclothing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
