# Generated by Django 5.2.1 on 2025-06-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_productclothing_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('proto', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
