# Generated by Django 5.2.1 on 2025-06-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_shopbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopbanner',
            name='proto',
        ),
        migrations.AddField(
            model_name='shopbanner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
