# Generated by Django 5.2.1 on 2025-06-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_shopbanner_proto_shopbanner_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopBanner',
        ),
    ]
