# Generated by Django 5.2.1 on 2025-06-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
